
# private-build-plans.toml
# Paste this to root `Iosevka` directory,
# For more info see https://typeof.net/Iosevka/customizer

[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

	[buildPlans.IosevkaCustom.variants]
	inherits = "ss14"

		[buildPlans.IosevkaCustom.variants.design]
		a = "double-storey-serifless"
		zero = "slashed"
    paren = "normal"
    brace = "straight"

[buildPlans.IosevkaCustom.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCustom.weights.Bold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCustom.widths.Normal]
shape = 658
menu = 8
css = "normal"

[buildPlans.IosevkaCustom.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"



