# private-build-plans.toml
# Paste this to root `Iosevka` directory,
# For more info see https://typeof.net/Iosevka/customizer

[buildPlans.Varys]
family = "Varys"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

	[buildPlans.Varys.variants]
	inherits = "ss14"

		[buildPlans.Varys.variants.design]
		a = "double-storey-serifless"
		zero = "slashed"
		paren = "normal"
		brace = "straight"
		lig-equal-chain = "without-notch"
		lig-double-arrow-bar = "with-notch"
		lig-single-arrow-bar = "with-notch"

  [buildPlans.Varys.ligations]
  inherits = "javascript"

[buildPlans.Varys.widths.Normal]
shape = 658
menu = 8
css = "normal"

[buildPlans.Varys.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.Varys.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

