format = """
$time\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$deno\
$nodejs\
$custom\
$lua\
$golang\
$rust\
$python\
$jobs\
$character\
$vi_mode"""

add_newline = false

[directory]
format = "[$read_only]($read_only_style)[$path]($style)"
read_only = "🔒 "
style = "fg:#ffffff"
truncation_length = 0

[git_branch]
style = "bright-white"
symbol = ""
format = '[$symbol $branch(:$remote_branch)]($style)'

[git_status]
conflicted = " "
ahead = " ${count} "
behind = " ${count} "
diverged = "  ${ahead_count}  ${behind_count} "
untracked = " ${count} "
stashed = " ${count} "
modified = " ${count} "
staged = " ${count} "
renamed = " ${count} "
deleted = " ${count} "
style = "bright-white"
format = ' ([$all_status$ahead_behind]($style))'

[python]
format = "[${pyenv_prefix}${version}( \\($virtualenv\\))]($style) "

[golang]
format = "- [go@$version]($style) "
version_format = "$raw"

[deno]
format = "- $symbol[$version](green) "
style = "green"
version_format = "${raw}"

[nodejs]
detect_extensions = ["mjs", "cjs"]
detect_files = ['package.json', '.node-version']
format = "- [node@](green)"
version_format = "raw"


# node version not working
[custom.node_custom]
detect_extensions = ["mjs", "cjs"]
command = 'node --version | cut -c 1-' # cuts the first character
detect_files = ['package.json', '.node-version'] 
format = '[$output](green) '

[lua]
format = '- [lua@$version](blue) '

[rust]
format = "- [rust@$version]($style) "

[character]
error_symbol = " [# ](bright-white)"
success_symbol = " [# ](bright-white)"
vimcmd_symbol = " [! ](bright-white)"
vimcmd_replace_one_symbol = " [! ](green)"
vimcmd_replace_symbol = " [! ](yellow)"
vimcmd_visual_symbol = " [! ](purple)"
