local palette = {
	bg_base = "#080808",
	bg_elevated = "#101010",
	bg_ghost = "#191919",
	bg_info = "#17255488",
	bg_warning = "#713f1244",
	bg_error = "#42191b88",
	bg_indigo = "#818cf8",

	border_default = "#252525",
	border_subtle = "#212121",
	border_panel = "#434343",
	border_warning = "#713f1277",
	border_error = "#42191b",

	surface_default = "#232323",
	surface_active = "#242536",
	surface_disabled = "#2e343eff",
	surface_search = "#343950",

	fg_default = "#b4b4b4",
	fg_editor = "#a7a7a7",
	fg_muted = "#9a9a9a",
	fg_placeholder = "#737373",
	fg_disabled = "#4e5a5f",
	fg_bright = "#dce0e5ff",
	fg_white = "#ffffff",
	fg_soft_white = "#f5f5f5",
	fg_light_gray = "#d5d5d5",

	line_number = "#4e5a5f",
	line_number_active = "#d0d4da",
	line_number_hover = "#acb0b4",
	indent_guide = "#303030",
	indent_guide_active = "#505050",
	document_highlight = "#30313c",

	keyword = "#ff8185",
	function_name = "#e0c3ff",
	string = "#a6d6ff",
	number = "#73AAE0",
	boolean = "#73AAE0",
	type = "#cfcfcf",
	property = "#eaeaea",
	constant = "#afafaf",
	constructor = "#bababa",
	comment = "#5d5d5d",
	comment_special = "#5f5f5f",
	punctuation = "#8a8a8a",
	tag = "#a1e7a7",
	label = "#74ade8ff",
	link = "#678cb1",
	predictive = "#5a6a87ff",
	hint_syntax = "#788ca6ff",

	status_added = "#81ffbb",
	status_modified = "#93c5fd",
	status_deleted = "#ff8185",
	status_warning = "#fed7aa",
	status_success = "#ffcfa7",
	status_conflict = "#dec184ff",
	status_neutral = "#545454",

	terminal_black = "#282c33ff",
	terminal_bright_black = "#525561ff",
	terminal_red = "#d07277ff",
	terminal_bright_red = "#673a3cff",
	terminal_dim_red = "#eab7b9ff",
	terminal_green = "#ffcfa7",
	terminal_bright_green = "#4d6140ff",
	terminal_dim_green = "#d1e0bfff",
	terminal_yellow = "#dec184ff",
	terminal_bright_yellow = "#e5c07bff",
	terminal_dim_yellow = "#f1dfc1ff",
	terminal_blue = "#74ade8ff",
	terminal_bright_blue = "#385378ff",
	terminal_dim_blue = "#bed5f4ff",
	terminal_magenta = "#be5046ff",
	terminal_bright_magenta = "#5e2b26ff",
	terminal_dim_magenta = "#e6a79eff",
	terminal_cyan = "#d5d5d5",
	terminal_bright_cyan = "#3a565bff",
	terminal_dim_cyan = "#b9d9dfff",
	terminal_dim_white = "#575d65ff",
}

local M = {
	palette = palette,

	groups = {
		normal = { fg = palette.fg_editor, bg = palette.bg_base },
		comment = { fg = palette.comment },
		keyword = { fg = palette.keyword },
		function_name = { fg = palette.function_name },
		function_call = { fg = palette.fg_default },
		type = { fg = palette.type },
		property = { fg = palette.property },
		string = { fg = palette.string },
		number = { fg = palette.number },
		boolean = { fg = palette.boolean },
		constant = { fg = palette.constant },
		variable = { fg = palette.fg_white },
		operator = { fg = palette.fg_light_gray },
		punctuation = { fg = palette.punctuation },
		tag = { fg = palette.tag },
		link = { fg = palette.link },
		diff_add = { fg = palette.status_added },
		diff_change = { fg = palette.status_modified },
		diff_delete = { fg = palette.status_deleted },
		diagnostic_error = { fg = palette.status_deleted, bg = palette.bg_error },
		diagnostic_warn = { fg = palette.status_warning, bg = palette.bg_warning },
		diagnostic_info = { fg = palette.status_neutral, bg = palette.bg_info },
		diagnostic_hint = { fg = palette.status_neutral, bg = palette.bg_info },
	},

	style = {
		background = palette.bg_base,
		elevated_surface = palette.bg_elevated,
		surface = palette.bg_base,
		element = palette.surface_default,
		element_active = palette.surface_active,
		element_disabled = palette.surface_disabled,
		ghost_element = palette.bg_ghost,
		text = palette.fg_default,
		text_muted = palette.fg_muted,
		text_placeholder = palette.fg_placeholder,
		text_disabled = palette.fg_placeholder,
		text_accent = palette.fg_white,
		icon = palette.fg_bright,
		icon_muted = "#a9afbcff",
		icon_disabled = palette.fg_disabled,
		panel_focused_border = palette.border_panel,
		editor_active_line = palette.surface_default,
		editor_highlighted_line = palette.border_default,
		editor_line_number = palette.line_number,
		editor_active_line_number = palette.line_number_active,
		editor_hover_line_number = palette.line_number_hover,
		editor_indent_guide = palette.indent_guide,
		editor_indent_guide_active = palette.indent_guide_active,
		editor_document_highlight = palette.document_highlight,
		search_match_background = palette.surface_search,
		link_hover = palette.label,
	},

	syntax = {
		attribute = palette.fg_editor,
		boolean = palette.boolean,
		comment = palette.comment,
		constant = palette.constant,
		constructor = palette.constructor,
		embedded = palette.fg_bright,
		emphasis = palette.fg_soft_white,
		enum = palette.fg_placeholder,
		function_name = palette.function_name,
		hint = palette.hint_syntax,
		keyword = palette.keyword,
		label = palette.label,
		link_text = palette.link,
		link_uri = palette.fg_light_gray,
		namespace = palette.fg_light_gray,
		number = palette.number,
		operator = palette.fg_light_gray,
		predictive = palette.predictive,
		preproc = palette.fg_bright,
		primary = palette.fg_white,
		property = palette.property,
		punctuation = palette.fg_white,
		punctuation_bracket = palette.punctuation,
		punctuation_delimiter = palette.punctuation,
		punctuation_list_marker = palette.terminal_red,
		punctuation_special = palette.comment_special,
		selector = palette.fg_white,
		selector_pseudo = palette.label,
		string = palette.string,
		string_escape = palette.fg_light_gray,
		string_regex = palette.fg_soft_white,
		string_special = palette.fg_soft_white,
		tag = palette.tag,
		text_literal = palette.status_success,
		title = palette.terminal_red,
		type = palette.type,
		variable = palette.fg_white,
		variable_special = palette.fg_soft_white,
		variant = palette.link,
	},
}

return M
