local colors = require("minimal_fedu")

return {
	prefix = "BlinkCmpKind",
	fg = colors.palette.grey[5],
	{ "File" },
	{ "Module" },
	{ "Namespace" },
	{ "Package" },
	{ "Class" },
	{ "Method" },
	{ "Property" },
	{ "Field" },
	{ "Constructor" },
	{ "Enum" },
	{ "Interface" },
	{ "Function" },
	{ "Variable" },
	{ "Constant" },
	{ "String" },
	{ "Number" },
	{ "Boolean" },
	{ "Array" },
	{ "Object" },
	{ "Key" },
	{ "Null" },
	{ "EnumMember" },
	{ "Struct" },
	{ "Event" },
	{ "Operator" },
	{ "TypeParameter" },
	{ "Unit" },
	{ "Text" },
	{ "Snippet" },
	{ "Keyword" },
}
