---@diagnostic disable: undefined-global

local lush = require("lush")
local hsl = lush.hsl

local palette = {
  bg = hsl("#121212"),
  surface = hsl("#101010"),
  surface_hi = hsl("#121212"),
  status = hsl("#151515"),
  border = hsl("#242424"),
  cursor = hsl("#818cf8"),
  selection = hsl("#343950"),
  scrollbar = hsl("#303030"),

  fg = hsl("#d8d8d8"),
  fg_hi = hsl("#eeeeee"),
  subtle = hsl("#989898"),
  muted = hsl("#5c5c5c"),
  gutter = hsl("#4f5a5f"),

  red = hsl("#f88888"),
  red_soft = hsl("#cd6d6f"),
  peach = hsl("#ffd0a8"),
  peach_muted = hsl("#e8c0a0"),
  lavender = hsl("#e0c0ff"),
  purple = hsl("#c8b0e0"),
  blue = hsl("#525490"),
  yellow = hsl("#d8be72"),
  green = hsl("#a8d8a2"),
  cyan = hsl("#9bcfd8"),
}

return lush(function()
  return {
    Normal({ fg = palette.fg, bg = palette.bg }),
    NormalNC({ fg = palette.subtle, bg = palette.bg }),
    NormalFloat({ fg = palette.fg, bg = palette.surface }),
    FloatBorder({ fg = palette.border.lighten(22), bg = palette.surface }),
    FloatTitle({ fg = palette.fg, bg = palette.surface, gui = "bold" }),

    ColorColumn({ bg = palette.surface }),
    Conceal({ fg = palette.muted }),
    Cursor({ fg = palette.bg, bg = palette.cursor }),
    CursorIM({ Cursor }),
    CursorColumn({ bg = palette.surface }),
    CursorLine({ bg = palette.surface }),
    CursorLineNr({ fg = palette.fg, bg = palette.surface, gui = "bold" }),
    Directory({ fg = palette.subtle, gui = "bold" }),
    EndOfBuffer({ fg = palette.bg }),
    ErrorMsg({ fg = palette.red, gui = "bold" }),
    FoldColumn({ fg = palette.muted, bg = palette.bg }),
    Folded({ fg = palette.subtle, bg = palette.surface }),
    IncSearch({ fg = palette.bg, bg = palette.peach }),
    LineNr({ fg = palette.gutter, bg = palette.bg }),
    MatchParen({ fg = palette.fg_hi, bg = palette.selection, gui = "bold" }),
    ModeMsg({ fg = palette.peach }),
    MoreMsg({ fg = palette.green }),
    NonText({ fg = palette.muted.lighten(16) }),
    Pmenu({ fg = palette.fg, bg = palette.surface }),
    PmenuSbar({ bg = palette.surface_hi }),
    PmenuSel({ fg = palette.fg_hi, bg = palette.selection }),
    PmenuThumb({ bg = palette.scrollbar }),
    Question({ fg = palette.peach }),
    QuickFixLine({ bg = palette.surface, gui = "bold" }),
    Search({ fg = palette.bg, bg = palette.yellow }),
    SignColumn({ fg = palette.gutter, bg = palette.bg }),
    SpecialKey({ fg = palette.border.lighten(18) }),
    SpellBad({ sp = palette.red, gui = "undercurl" }),
    SpellCap({ sp = palette.blue.lighten(28), gui = "undercurl" }),
    SpellLocal({ sp = palette.cyan, gui = "undercurl" }),
    SpellRare({ sp = palette.purple, gui = "undercurl" }),
    StatusLine({ fg = palette.subtle, bg = palette.status }),
    StatusLineNC({ fg = palette.muted, bg = palette.surface }),
    Substitute({ fg = palette.bg, bg = palette.red }),
    TabLine({ fg = palette.subtle, bg = palette.surface_hi }),
    TabLineFill({ bg = palette.surface_hi }),
    TabLineSel({ fg = palette.fg, bg = palette.bg, gui = "bold" }),
    TermCursor({ Cursor }),
    Title({ fg = palette.fg, gui = "bold" }),
    VertSplit({ fg = palette.border, bg = palette.bg }),
    Visual({ bg = palette.selection }),
    VisualNOS({ Visual }),
    WarningMsg({ fg = palette.yellow }),
    Whitespace({ fg = palette.border.lighten(10) }),
    WildMenu({ fg = palette.bg, bg = palette.lavender }),
    WinBar({ fg = palette.subtle, bg = palette.surface_hi }),
    WinBarNC({ fg = palette.muted, bg = palette.surface_hi }),
    WinSeparator({ fg = palette.border, bg = palette.bg }),

    Comment({ fg = palette.muted, gui = "italic" }),
    Constant({ fg = palette.peach }),
    Nullish({ fg = palette.subtle }),
    String({ fg = palette.peach }),
    Character({ fg = palette.peach }),
    Number({ fg = palette.peach_muted }),
    Boolean({ fg = palette.red }),
    Float({ fg = palette.peach_muted }),
    Identifier({ fg = palette.fg }),
    Function({ fg = palette.lavender }),
    Statement({ fg = palette.red }),
    Conditional({ fg = palette.red }),
    Repeat({ fg = palette.red }),
    Label({ fg = palette.peach }),
    Operator({ fg = palette.subtle }),
    Keyword({ fg = palette.red }),
    Exception({ fg = palette.red }),
    PreProc({ fg = palette.purple }),
    Include({ fg = palette.red }),
    Define({ fg = palette.purple }),
    Macro({ fg = palette.purple }),
    PreCondit({ fg = palette.purple }),
    Type({ fg = palette.fg_hi }),
    StorageClass({ fg = palette.red }),
    Structure({ fg = palette.purple }),
    Typedef({ fg = palette.purple }),
    Special({ fg = palette.subtle }),
    SpecialChar({ fg = palette.peach }),
    Tag({ fg = palette.lavender }),
    Delimiter({ fg = palette.subtle }),
    SpecialComment({ fg = palette.muted, gui = "italic" }),
    Debug({ fg = palette.red }),
    Underlined({ fg = palette.lavender, gui = "underline" }),
    Ignore({ fg = palette.muted }),
    Error({ fg = palette.red }),
    Todo({ fg = palette.bg, bg = palette.peach, gui = "bold" }),

    Added({ fg = palette.green }),
    Changed({ fg = palette.yellow }),
    Removed({ fg = palette.red }),
    DiffAdd({ fg = palette.green, bg = palette.green.darken(70).desaturate(55) }),
    DiffChange({ fg = palette.yellow, bg = palette.yellow.darken(72).desaturate(55) }),
    DiffDelete({ fg = palette.red, bg = palette.red.darken(72).desaturate(55) }),
    DiffText({ fg = palette.fg_hi, bg = palette.blue.darken(32).desaturate(30) }),

    DiagnosticError({ fg = palette.red }),
    DiagnosticWarn({ fg = palette.yellow }),
    DiagnosticInfo({ fg = palette.cyan }),
    DiagnosticHint({ fg = palette.lavender }),
    DiagnosticOk({ fg = palette.green }),
    DiagnosticUnderlineError({ sp = palette.red, gui = "undercurl" }),
    DiagnosticUnderlineWarn({ sp = palette.yellow, gui = "undercurl" }),
    DiagnosticUnderlineInfo({ sp = palette.cyan, gui = "undercurl" }),
    DiagnosticUnderlineHint({ sp = palette.lavender, gui = "undercurl" }),
    DiagnosticVirtualTextError({ fg = palette.red_soft, bg = palette.red.darken(76).desaturate(50) }),
    DiagnosticVirtualTextWarn({ fg = palette.yellow, bg = palette.yellow.darken(76).desaturate(50) }),
    DiagnosticVirtualTextInfo({ fg = palette.cyan, bg = palette.cyan.darken(76).desaturate(50) }),
    DiagnosticVirtualTextHint({ fg = palette.lavender, bg = palette.lavender.darken(76).desaturate(50) }),

    GitSignsAdd({ fg = palette.green }),
    GitSignsChange({ fg = palette.yellow }),
    GitSignsDelete({ fg = palette.red }),

    TelescopeBorder({ fg = palette.border.lighten(22), bg = palette.surface }),
    TelescopeNormal({ fg = palette.fg, bg = palette.surface }),
    TelescopePromptBorder({ fg = palette.border.lighten(22), bg = palette.surface_hi }),
    TelescopePromptNormal({ fg = palette.fg, bg = palette.surface_hi }),
    TelescopePromptPrefix({ fg = palette.peach }),
    TelescopeSelection({ fg = palette.fg_hi, bg = palette.selection }),

    NvimTreeNormal({ fg = palette.subtle, bg = palette.surface }),
    NvimTreeFolderName({ fg = palette.subtle }),
    NvimTreeOpenedFolderName({ fg = palette.yellow, gui = "bold" }),
    NvimTreeRootFolder({ fg = palette.yellow, gui = "bold" }),
    NvimTreeCursorLine({ bg = palette.selection }),

    NeoTreeNormal({ fg = palette.subtle, bg = palette.surface }),
    NeoTreeDirectoryName({ fg = palette.subtle }),
    NeoTreeDirectoryIcon({ fg = palette.subtle }),
    NeoTreeRootName({ fg = palette.yellow, gui = "bold" }),
    NeoTreeCursorLine({ bg = palette.selection }),

    WhichKey({ fg = palette.lavender }),
    WhichKeyDesc({ fg = palette.fg }),
    WhichKeyGroup({ fg = palette.peach }),
    WhichKeySeparator({ fg = palette.muted }),
    WhichKeyFloat({ bg = palette.surface }),

    LazyNormal({ fg = palette.fg, bg = palette.surface }),
    MasonNormal({ fg = palette.fg, bg = palette.surface }),

    SnacksDashboardDesc({ fg = palette.subtle }),
    SnacksDashboardFile({ fg = palette.subtle }),
    SnacksDashboardIcon({ fg = palette.subtle }),
    SnacksDashboardFooter({ fg = palette.subtle, gui = "bold" }),
    SnacksDashboardHeader({ fg = palette.fg, gui = "bold" }),
    SnacksDashboardKey({ fg = palette.subtle }),
  }
end)
