local icons = require("theme.icons")

-- minimize code-size on `lsp-config.lua`
return {
	File = { icon = icons.File },
	Module = { icon = icons.Constructor, hl = "Include" },
	Namespace = { icon = icons.Namespace, hl = "Include" },
	Package = { icon = icons.Package, hl = "Include" },
	Class = { icon = icons.Class, hl = "Type" },
	Method = { icon = icons.Function, hl = "Function" },
	Property = { icon = icons.Property, hl = "Identifier" },
	Field = { icon = icons.Property, hl = "Identifier" },
	Constructor = { icon = icons.Constructor, hl = "Special" },
	Enum = { icon = icons.Enum, hl = "Type" },
	Interface = { icon = icons.Interface, hl = "Type" },
	Function = { icon = icons.Function },
	Variable = { icon = icons.Variable, hl = "Constant" },
	Constant = { icon = icons.Constant, hl = "Constant" },
	String = { icon = icons.String, hl = "String" },
	Number = { icon = icons.Number, hl = "Number" },
	Boolean = { icon = icons.Boolean, hl = "Boolean" },
	Array = { icon = icons.Array, hl = "Constant" },
	Object = { icon = icons.Object, hl = "Type" },
	Key = { icon = icons.Key, hl = "Type" },
	Null = { icon = icons.Null, hl = "Type" },
	EnumMember = { icon = icons.EnumMember, hl = "Identifier" },
	Struct = { icon = icons.Struct, hl = "Structure" },
	Event = { icon = icons.Event, hl = "Type" },
	Operator = { icon = icons.Operator, hl = "Identifier" },
	TypeParameter = { icon = icons.TypeParameter, hl = "Identifier" },
	Component = { icon = icons.Module, hl = "Function" },
	Fragment = { icon = icons.Module, hl = "Constant" },
	TypeAlias = { icon = icons.TypeParameter, hl = "Type" },
	Parameter = { icon = icons.TypeParameter, hl = "Identifier" },
	StaticMethod = { icon = icons.Function, hl = "Function" },
	Macro = { icon = " ", hl = "Function" },
}
